let w0 = window()!
activate(w0.pid)
let euWest = CGPoint(x: w0.bounds.minX + 719, y: w0.bounds.minY + 136)
let service = CGPoint(x: w0.bounds.minX + 364, y: w0.bounds.minY + 136)
NSPasteboard.general.clearContents(); NSPasteboard.general.setString("before", forType: .string)
click(euWest); usleep(300_000)
key(kA, .maskCommand); key(kC, .maskCommand); usleep(300_000)
print("copy eu-west:", pasteboard())
NSPasteboard.general.clearContents(); NSPasteboard.general.setString("clip-123", forType: .string)
click(service); usleep(300_000)
key(kV, .maskCommand); usleep(400_000)
shot(window()!, "/tmp/rw/clip1.png")
NSPasteboard.general.clearContents(); NSPasteboard.general.setString("x", forType: .string)
key(kA, .maskCommand); key(kC, .maskCommand); usleep(300_000)
print("copy pasted text:", pasteboard())
key(kA, .maskCommand); key(CGKeyCode(7), .maskCommand); usleep(400_000)
print("after cut:", pasteboard())
shot(window()!, "/tmp/rw/clip2.png")
