// @generated by `gpui-rhai embed`; edit files under `ui/` instead.

pub fn app_manifest() -> gpui_rhai::AppManifest {
    let manifest = gpui_rhai::AppManifest::new(gpui_rhai::ModuleId::parse("main").expect("generated entry id"));
    manifest
}

pub fn script_source() -> gpui_rhai::EmbeddedScriptSource {
    gpui_rhai::EmbeddedScriptSource::new(std::collections::BTreeMap::from([
        (gpui_rhai::ModuleId::parse("main").expect("generated module id"), include_str!("../ui/main.rhai").to_owned()),
    ]))
}

pub const THEME_SOURCE: &str = include_str!("../ui/theme.rhai");

pub const COMPONENT_STYLES_SOURCE: &str = include_str!("../ui/styles.rhai");

pub const LOCALES: &[(&str, &str)] = &[
    ("ar.rhai", include_str!("../ui/locales/ar.rhai")),
    ("en.rhai", include_str!("../ui/locales/en.rhai")),
    ("zh_cn.rhai", include_str!("../ui/locales/zh_cn.rhai")),
];

pub const THEMES: &[(&str, &str)] = &[
    ("aetheria.rhai", include_str!("../ui/themes/aetheria.rhai")),
    ("catppuccin_latte.rhai", include_str!("../ui/themes/catppuccin_latte.rhai")),
    ("catppuccin_mocha.rhai", include_str!("../ui/themes/catppuccin_mocha.rhai")),
    ("default_light.rhai", include_str!("../ui/themes/default_light.rhai")),
    ("ethereal.rhai", include_str!("../ui/themes/ethereal.rhai")),
    ("everforest.rhai", include_str!("../ui/themes/everforest.rhai")),
    ("futurism.rhai", include_str!("../ui/themes/futurism.rhai")),
    ("gruvbox.rhai", include_str!("../ui/themes/gruvbox.rhai")),
    ("hackerman.rhai", include_str!("../ui/themes/hackerman.rhai")),
    ("hermarchy.rhai", include_str!("../ui/themes/hermarchy.rhai")),
    ("nord.rhai", include_str!("../ui/themes/nord.rhai")),
    ("retro_82.rhai", include_str!("../ui/themes/retro_82.rhai")),
    ("tokyo_night.rhai", include_str!("../ui/themes/tokyo_night.rhai")),
    ("tokyo_storm.rhai", include_str!("../ui/themes/tokyo_storm.rhai")),
];

pub const ASSETS: &[(&str, &[u8])] = &[
];

pub fn asset_sources() -> Vec<(String, gpui_rhai::AssetData)> {
    vec![
    ]
}

pub const FONTS: &[(&str, &[u8])] = &[
];

pub fn font_sources() -> Vec<gpui_rhai::FontSource> {
    vec![
    ]
}
